{% set name = "mikeio" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5e71b648c73bb82fdf73641ac5272fef7eab0ca637b53631d28e22a66e04617d
  
build:
  
  #noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: True  # [py<36] [not win]"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy
    - pandas
    - shapely
    - matplotlib

test:
  imports:
    - mikeio
  requires:
    - pytest

about:
  home: https://github.com/DHI/mikeio
  license: BSD-3-Clause
  license_family: BSD
  license_file: License.txt
  summary: Read, write and manipulate dfs0, dfs1, dfs2, dfs3, dfsu and mesh files. Read res1d and xns11 files.

  doc_url: https://dhi.github.io/mikeio/
  dev_url: https://github.com/DHI/mikeio

extra:
  recipe-maintainers:
    - ecomodeller
