{% set name = "mikecore" %}
{% set version = "0.1.2b2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/aa/d4/ec7ad81d3622a6ad2c4dd343cc50760381372ed64ae80b5dfa3acfd9d1d3/mikecore-{{version}}-py3-none-any.whl
  sha256: 905d51889fd5faf3f0218ae331e834a8631e55386c0cdf72b5f4ddae0b2d3741
  
build:
  
  #noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: True  # [py<36] [not win]"

requirements:
  host:
    - python  >=3.6
    - pip
  run:
    - python  >=3.6
    - numpy

test:
  imports:
    - mikecore
  requires:
    - pytest

about:
  home: https://github.com/DHI/mikecore-python
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: MIKE Core in Python

  doc_url: https://github.com/DHI/mikecore-python
  dev_url: https://github.com/DHI/mikecore-python

extra:
  recipe-maintainers:
    - ecomodeller
